### PR TITLE
updated Astar Algorithm

### PR DESCRIPTION
**Pull request by jaspreetj**
It should 
- work for complicated obstacles.
- have no waveguide overlaps.
- have less number of bends than the previous code which depend on the grid increment (10 um) and the bend radius(5um).

The following changes were made:
- Reduced grid density and fast path generation.
- Each grid cell is 10x10um or Minimum grid coordinate increment is 10um. There should always be a zero at ones place therefore coordinates like 20.1, 21, 1, 5, 2, 111 are not valid
- Valid coordinates should look like 0, 10, 20, 110, 120, 300 
- Also check the other waveguides' coordinates. They should also be aligned to the grid.

### CODE REVIEW

**Comment by jaspreetj** [comment]
Thank you for your suggestion to reduce the grid density. I reduced it and performed memory tests on the python script in cmd to eliminate the use of packages which were consuming a lot of memory. 

In order to make it more faster, I will try to implement navigation meshes rather than grids but for now and the working cells of 610x405um, this algorithm should work without any problems.

-Jaspreet

**Comment by lukasc-ubc** [comment]
Hi Jaspreet,

My suggestion is not to reduce the density of the grid, but rather to make it a sparse grid.  I would put grid points only at specific locations, as described in the waypoints section here: http://www.redblobgames.com/pathfinding/grids/algorithms.html

We need an algorithm that doesn't scale by O(N^2) with thousands of grid points.  Imagine a layout that is 1x1 cm.

**Comment by jaspreetj** [comment]
Hi Lukas,

 I apologize for my mistake. I have just implemented the visible graph method. It gives results in an instant and it does not scale by O(N^2). It generates a navigation mesh or a sparse grid which depends only on the total number of the vertices of the obstacles present in the space.

**Comment by lukasc-ubc** [comment]
Wow, that's cool.  Let me try it.

**Comment by lukasc-ubc** [comment]
is there any way to have this NOT use shapely?  it isn't available on the Mac by default. 

Or is it critical?

**Comment by jaspreetj** [comment]
A lot of the polygon processing and obstacle detection is being done in shapely. At this stage, it is a must to have Shapely installed.

I can write a piece of code in the script which would download and install the required packages.

**Comment by lukasc-ubc** [comment]
Ok. 
I guess I'll need to figure out how to do it for the Mac. 


Lukas Chrostowski
Associate Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by jaspreetj** [comment]
I could try to simplify the code which would not require any additional libraries like shapely but that would surely take some time. I need to make it work with shapely first and then I will optimize the code for the mac systems.

-Jaspreet

**Comment by lukasc-ubc** [comment]
Sounds good. I'm sure there is a way to get shapely working on the Mac. I do have shapely working it's just that klayout can't find it. 


Lukas Chrostowski
Associate Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by jaspreetj** [comment]
If you have shapely installed on the python IDLE then you can use the following code in python IDLE to generate wg path solution points and then plot them using klayout.

https://www.dropbox.com/s/a8i2ytpqau7p6cl/visiblegraph_v4.py?dl=0

-Jaspreet

**Pull request merged**
