### PR TITLE
Added GUI for MC Simulations

### PR DESCRIPTION
**Pull request by jaspreetj**
For klayout 0.24/0.25, it requires tcl8.6 and tk8.6 to work.

Download it from here:
https://www.dropbox.com/s/2o8sj0d5t8ai1pg/tcl8.6.zip?dl=1

Navigate to Klayout installation folder and extract the contents in the following directory:
      \KLayout (64bit)\lib\python\Lib\

untitled

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Great start, but how would this work on Linux and OSX?

We don't want to modify the KLayout installation requirements.

**Comment by jaspreetj** [comment]
KLayout has inbuilt Qt bindings which you have previously used to create GUIs but they are embedded in the pya library. I am currently working on it.

**Comment by jaspreetj** [comment]
Fixed it!
Now it works without any extra libraries. I have even implemented an input validator which notifies the user whether the input is acceptable or not.

untitled

**Comment by luzeqin** [comment]
Looks great!

**Comment by jaspreetj** [comment]
- Updated GUI layout
- Input Validator
- Fully integrated the GUI with the scripts.

**Note: The scripts won't be visible in the SiEPIC menu anymore.**

**Pull request merged**
