### PR TITLE
Updated TE mode design generator and Added A star assisted waveguide path generator.

### PR DESCRIPTION
**Pull request by jaspreetj**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Thanks Jaspreet!

shapely / GEOS are not installed by default on OSX.  

I also checked on windows 8, and it didn't have shapely installed.

Did you have to install this?  Is it needed for this implementation?

**Comment by lukasc-ubc** [comment]
I got shapely working on OSX.  

Nice start to this project.

It looks like you ran into the challenge I anticipated. Namely, that you end up with lots of left/right turns.  You need some heuristic to minimize the number of bends.  Also bend radius, and finally, the direction of the pin.

**Comment by lukasc-ubc** [comment]
I also read that the heuristic estimate you used isn't recommended.  It was suggested that the diagonal distance should be used, instead of the sum of ∆x + ∆y.


      from math import sqrt

      self.mvalue = sqrt(abs(self.data[0]-self.goal[0])**2 + abs(self.data[1]-self.goal[1])**2)

**Comment by lukasc-ubc** [comment]
How do you implement the grid?  It must be a pretty fine grid, since it takes a long time to find it.  For a short waveguide blocking piece, it runs quickly. But when I extended your blocking waveguide, it took about 10X longer.  

It actually overlapped the waveguide.  See screenshot:

https://www.dropbox.com/s/l38g0b8n2k7xyov/Screenshot%202015-12-03%2011.25.47.png?dl=1

**Comment by lukasc-ubc** [comment]
Your script doesn't like to run when the IDE is open.  It generates an error:

Caught the following exception:
None (Class exceptions.GeneratorExit)
Press 'Ok' to continue and 'Cancel' to stop in the debugger

at line 297.  

Instead of using try, check to see if the variables exist...

**Comment by jaspreetj** [comment]
I noticed this as well. Apparently, sorting of opened and closed lists
takes a very long time as the lists get lengthier. I am going to use
priority lists /sets for that.

I used manhattan estimate because I am not allowing diagonal moves.

**Pull request merged**
