### PR TITLE
Astar Waveguide Path Generation- Fixed Errors

### PR DESCRIPTION
**Pull request by jaspreetj**
I have fixed the script errors. It should work now. 

**Note:If you draw waveguides properly eg. keep a minimum distance of 3um between different waveguide branches, the script should work without any problems/errors.**

The script sometimes generates incomplete waveguides, it happens if waveguide branches are too close to each other. 

If you still encounter errors or incomplete waveguides, you can tweak the following values to get a proper geometry.

_The following variable controls the overall geometry of the generated waveguide._
1)  **shell_pt**-> higher values give smooth geometry but can result in errors if the distance between waveguide branches is too little. Recommended range is (5.0 - 15.0)
eg. change `shell_pt = generateBounds(shell, 5)` to `shell_pt = generateBounds(shell, 8)`

_The following variable controls the sparse points' geometry._
2) **barred_points** -> recommended range is 1.0 - 2.5, anything higher than this range can cause errors or incomplete waveguides.
eg. change `barred_points = generateBounds(temp_points, 1.5)` to `barred_points = generateBounds(temp_points, 2.0)`
_The following variable controls the geometry of the generated manhattan path._

3) **mangen_points** -> recommended range is 1.0 - 2.5
eg. change `mangen_points = generateBounds(points_for_mangen, 1.5)` 
       to `mangen_points = generateBounds(points_for_mangen, 2.0)`

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Error in line 504 "global name 'path' is not defined".

**Comment by jaspreetj** [comment]
Hi Lukas,

I looked into this, I believe it happened because the astar algorithm was intrerrupted before it could finish. It happens if the algorithm fails to find a valid path and gets interrupted.

I think it has something to do with the following:
1. values of the above mentioned three variables.
2. other waveguides are too close to each other, try to put a distance of about 5um between the obstacles.

I compiled a video showing the values I am currently using.
Try to use these values.
https://www.dropbox.com/s/zlz3o2yptl8khiz/Astar_test.mp4?dl=1

**Comment by lukasc-ubc** [comment]
Cool, it works!

to do — a method of specifying which direction the auto-route should go.  One way is to put silicon blocks around the components… but a better way would be to look at the pin (which is a path), and then determine whether to go left or right based on where the DevRec layer is.

See screenshot.

**Comment by jaspreetj** [comment]
I am currently debugging the previous code and simplifying it. Once I finish that I will implement this.

**Pull request merged**
