### PR TITLE
Bent couplers PCells

### PR DESCRIPTION
**Pull request by mustafacc**
Bent couplers PCells include:

-Bent coupled half ring resonator
-Bent waveguide bus
-Waveguide arc 

All PCells include functional device rec and pin rec layers.

Can be used to create bent-coupled rings and MZI-BC rings.

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Could you modify this so that it adds it to the EBeam library, rather than creating a separate library?  thanks!

**Comment by mustafacc** [comment]
Done. 

Ajay fixed a bug with the EBeam_DC_Seriesrings component analysis script, previously there was no coupling between the rings if the component was used in Interconnect. This was fixed by changing the analysis script line 14 to "S31=Port3.b/Port1.a;" and line 33 to "S32=Port3.b/Port2.b;"

**Comment by lukasc-ubc** [comment]
Mustafa, 

> Edit: on a related note, I'm trying to make a PCell component of tapered rings like the ones in the picture attached. The way I want to go about this is by drawing a circle of radius R1 centered at P1, and then erase a circle of radius R2 centered at P2 out of the original circle. But I'm not quite sure which function to use to erase a polygon structure out of another polygon, is there a function to do that?

Yes. Take a look at the photonic crystal implementations. these are done by taking cutting circles out of a another polygon.  You could do the same.

**Comment by mustafacc** [comment]
Is the photonic crystal implementation in the SiEPIC library? I can't seem to find it.

**Comment by lukasc-ubc** [comment]
ah sorry, it wasn't.  Just added an example, which has been added as a PCell:

https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/commit/5f6a5deb9df2364548980dc66cd0009869af3b0f

**Pull request merged**
