### PR TITLE
PCell DC Series Rings

### PR DESCRIPTION
**Pull request by jaspreetj**
#79

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
The layout portion looks good.

How is the model coming along?  I'll wait to merge it until you have the model complete, ok?

**Comment by jaspreetj** [comment]
I have finished the cml model but having some trouble generating S-params. I think I messed up mode expansions in FDTD. I am going to run another set of simulations and verify if it works properly.

**Comment by lukasc-ubc** [comment]
Run them using mesh accuracy level 1 at first to debug things. 


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by luzeqin** [comment]
Hi Jaspreet, any update for this model?

**Pull request merged**
