### PR TITLE
Revert "group connected components/waveguides"

### PR DESCRIPTION
**Pull request by lukasc-ubc**
Reverts lukasc-ubc/SiEPIC_EBeam_PDK#94

Close to working, but 3 errors (1 error with the IDE closed)

image

### CODE REVIEW

**Comment by jaspreetj** [comment]
Can you send me the error details and the GDS file you were testing it on?

**Comment by lukasc-ubc** [comment]
Errors occurred for:
 - 12 MZI Jaspreet example, with 4 layouts
 - then added 1 laser, 1 detector on one of the designs.

**Comment by jaspreetj** [comment]
Add this line where we define layers. This fixed the error for me.
LayerTextN = ly.layer(LayerText)

**Comment by lukasc-ubc** [comment]
Hi Jaspreet,

When you have it working, can you please turn this into another menu item:

  SiEPIC > Simulation >  INTERCONNECT simulations with Abridged Netlist

and have it do the same thing as the regular simulations

When you ready, can you do another Pull request?

After we get it tested by many people, we can merge this with the regular simulations.  I think we will want to use this every time INTERCONNECT is called (including Monte Carlo).

So perhaps this upgrade should be merged in with the Netlist Generation code.  With a debug FLAG at the top of the function that lets us turn it off.  (who knows, maybe later it will be a configuration option somewhere).

thanks!

**Comment by jaspreetj** [comment]
What information is not included in the shortened Netlist?
So far, we have a code that separates the connected circuits from the ones with no detector/laser.
Why aren't we using the regular netlist generation function? because it can generate netlist only for the connected circuits.

**Comment by lukasc-ubc** [comment]
Hi Jaspreet,
I think what you have makes sense. Namely, the original netlist, minus the components that aren’t connected.  So all we need next is to launch the simulation from KLayout.

**Pull request merged**
