### PR TITLE
Upgrade ebeam_rib_phase_shifter

### PR DESCRIPTION
**Pull request by Guowu-Mcgill**
1. Fold phase shifter for N time (N is supposed to be an odd number) to increase power efficiency.

2. All the parameters/constants are defined at the beginning of the Pcell; a comment/explanation is added to each parameter.

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Thanks @Guowu-Mcgill, that's great.

In your file, you had symbols such as <, >, ohm, etc. KLayout lym are XML files so encode these characters.  Within KLayout, these are converted back <, >, etc.  I made the fix. It is also possible to use .py files, and import them.

I'll make some updates to your device (waveguides).

In your next update, can you please start with this version from GitHub?  

thanks,
Lukas

**Comment by Guowu-Mcgill** [comment]
Dear Professor Lukas,

Thanks for your feedback!

I just copy the code in Klayout and paste it to github. Sorry about that mistake! Next time, I will start from this version on Github!

Thanks!

Guowu Zhang
PhD candidate
McGill university
Photonic Datacom Team
________________________________
发件人: Lukas Chrostowski <notifications@github.com>
发送时间: Saturday, May 16, 2020 7:31:30 PM
收件人: lukasc-ubc/SiEPIC_EBeam_PDK <SiEPIC_EBeam_PDK@noreply.github.com>
抄送: Guowu Zhang <guowu.zhang@mail.mcgill.ca>; Mention <mention@noreply.github.com>
主题: Re: [lukasc-ubc/SiEPIC_EBeam_PDK] Upgrade ebeam_rib_phase_shifter (#211)


Thanks @Guowu-Mcgill<https://github.com/Guowu-Mcgill>, that's great.

In your file, you had symbols such as <, >, ohm, etc. KLayout lym are XML files so encode these characters. Within KLayout, these are converted back <, >, etc. I made the fix. It is also possible to use .py files, and import them.

I'll make some updates to your device (waveguides).

In your next update, can you please start with this version from GitHub?

thanks,
Lukas

―

**Comment by lukasc-ubc** [comment]
Ah, that makes sense and why it worked for you and not me.  I'll have some fixes soon, and you'll see the specific changes.

**Comment by Guowu-Mcgill** [comment]
Thanks!

So, you mean the code is not working properly on your side? I can send you the .py version and mark the U fold part. Let me know if you have any concerns, I am available now!

Regards,

Guowu Zhang
PhD candidate, Photonic Data Comm. Team
Department of Electronic Engineering, McGill University
3480 Rue University, Montreal H3A 0E9, QC, Canada

**Comment by lukasc-ubc** [comment]
@Guowu-Mcgill 
I just made some fixes throughout: db695f6 

still to do: waveguides.

**Comment by Guowu-Mcgill** [comment]
@lukasc-ubc,

Hi Professor Lukas,

If we replace the code from 6938 - 7010 usingthe code below, we could add path at the two edges. But i have no idea how to change it to waveguide in the Pcell. (Now, the code is using BOX and arc_wg to piece together the U turn. For which i think it's not so flexible and somewaht cumbersome.) I hope this will help!


        if (i+NNN)%2:
           u_path = Path([Point(-l/2 - in_taper, y_origin), 
           Point(-l/2 - in_taper - routing_step * (NNN - i + 1), y_origin), 
           Point(-l/2 - in_taper - routing_step * (NNN - i + 1), y_origin + routing_step * 2), 
           Point(-l/2 - in_taper - routing_step * (NNN - i), y_origin + routing_step * 2), 
           Point(-l/2 - in_taper - routing_step * (NNN - i), y_end), 
           Point(-l/2 - in_taper, y_end)], floding_w1)
           
           self.cell.shapes(LayerSiN).insert(u_path)
        else:           
           u_path = Path([Point(l/2 + in_taper, y_origin), 
           Point(l/2 + in_taper + routing_step * (NNN - i + 1), y_origin), 
           Point(l/2 + in_taper + routing_step * (NNN - i + 1), y_origin + routing_step * 2), 
           Point(l/2 + in_taper + routing_step * (NNN - i), y_origin + routing_step * 2), 
           Point(l/2 + in_taper + routing_step * (NNN - i), y_end), 
           Point(l/2 + in_taper, y_end)], floding_w1)

           self.cell.shapes(LayerSiN).insert(u_path)

**Comment by lukasc-ubc** [comment]
Yes, I am modifying the waveguide function so it can be accessed via script.

**Comment by lukasc-ubc** [comment]
making progress
image

**Comment by Guowu-Mcgill** [comment]
Awesome and amazing!! Thanks!

Regards,

Guowu Zhang
PhD candidate, Photonic Data Comm. Team
Department of Electronic Engineering, McGill University
3480 Rue University, Montreal H3A 0E9, QC, Canada

**Comment by lukasc-ubc** [comment]
just pushed. needs GitHub version of SiEPIC-tools

**Comment by Guowu-Mcgill** [comment]
Thanks! i will update package in Klayout and check!

**Comment by lukasc-ubc** [comment]
image

image

**Comment by Guowu-Mcgill** [comment]
Dear Professor Lukas,

Many thanks for your revision and improvements! I change the code for folded design so that the distance of NPP and VC to silicon satisfy the requirement from ANT.

Also, fix waveguide width mismatch for the left center input taper! I created and pull request for all these changes!

[cid:image001.png@01D62C49.154EAA40]



[cid:image004.png@01D62C49.72167F00]

[cid:image005.png@01D62C49.48C3E200]

Regards,

Guowu Zhang
PhD candidate, Photonic Data Comm. Team
Department of Electronic Engineering, McGill University
3480 Rue University, Montreal H3A 0E9, QC, Canada

**Pull request merged**
