### PR TITLE
PCM Spirals Updated

### PR DESCRIPTION
**Pull request by StephenHLin**
-Significantly speeds up drawing
-Fixed many alignment issues
-Adopted the new SiEPIC pin standards
=Layout Script is still WIP. Coming at a later date.

Link: https://github.com/StephenHLin/Adiabatic-Bragg-Grating-Spiral

### CODE REVIEW

**Comment by StephenHLin** [comment]
Hi Lukas, I was attempting to update the Layout script as well and noticed you changed the function 'layout_waveguide_rel'.
What's the current replacement for this function? I'm currently trying inserting a cell via Waveguide() from the EBeam library, but it creates a lot more clutter (due to labels that are created along with it).

**Comment by lukasc-ubc** [comment]
The labels are there for a variety of reasons: verification of the circuit, and being able to do simulations.

I can create an example of how to draw a layout…  I would create a path, then call the path-to-waveguide function.

**Comment by lukasc-ubc** [comment]
Hi Stephen,

I created an example in the EBeam PDK.  See the menu item Example Layout.

To use it:

- get the latest SiEPIC-Tools and EBeam (master on GitHub for both)
- create a layout using the EBeam technology
- run the script
- open the editor and find it under the EBeam PDK.

there is an issue where it fails verification.  but the basic idea is there.

**Comment by aasalaur** [comment]
3D modeling
Hello
Is there hope
  Create spirals (F9) function works
3D modeling
Viktor Schauberger Vortex
work
big interest
this topic

**Pull request closed without merging**
