### PR TITLE
Path optimization filter to remove sharp/hard edges from the generated path

### PR DESCRIPTION
**Pull request by jaspreetj**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Still not working… See screenshot

**Comment by lukasc-ubc** [comment]
I also added your script to the menu…

**Comment by jaspreetj** [comment]
I cannot find the attached screenshot. I tested the script on various obstacles and it works without any problems. Could you please send me the GDS file you are testing the script on? I think there might be some bits which are not getting executed properly on macOS.

**Comment by lukasc-ubc** [comment]
Lukas Chrostowski, P.Eng.,  Associate Professor
Program Director, NSERC Silicon Electronic-Photonic Integrated Circuits (SiEPIC) Program <http://www.siepic.ubc.ca/>
"Silicon Photonics Design" textbook is now available <http://www.cambridge.org/us/academic/subjects/engineering/electronic-optoelectronic-devices-and-nanotechnology/silicon-photonics-design-devices-systems>.

University of British Columbia
Electrical and Computer Engineering <http://www.ece.ubc.ca/>,
4039-2332 Main Mall, Kaiser Building
Vancouver, B.C., Canada, V6T-1Z4
Office: Room 4039 Kaiser Building
Work: 604-822-8507
http://www.mina.ubc.ca/lukasc <http://www.mina.ubc.ca/lukasc>

lukasc@ece.ubc.ca <mailto:lukasc@ece.ubc.ca>


 <http://www.cambridge.org/us/academic/subjects/engineering/electronic-optoelectronic-devices-and-nanotechnology/silicon-photonics-design-devices-systems>  <http://www.cambridge.org/9781316237113>

**Pull request merged**
